// Mock data — a fictional methodology bundle binding ("test-bundle") on a project
// that's mid-build. Reflects the actual data shape in SPEC.md §7.4.

const PROJECT = {
  id: 'p_throughline',
  name: 'Throughline',
  short: 'TL',
  bundle_id: 'test-bundle',
  repo_path: '~/code/throughline',
  branch: 'phase/15-hygiene',
  github: 'kunda/throughline',
};

const SESSIONS = [
  { id: 's1', name: 'Phase 15 — periodic review',  active: true,  open: 7,  pr_state: 'review', branch: 'phase/15-hygiene' },
  { id: 's2', name: 'Drift inbox cleanup',         active: true,  open: 4,  pr_state: null,     branch: 'drift/cleanup'    },
  { id: 's3', name: 'Bundle externalisation v2',   active: false, open: 11, pr_state: 'merged', branch: 'bundle/extern-v2' },
  { id: 's4', name: 'Companion runtime hardening', active: false, open: 3,  pr_state: 'open',   branch: 'companion/hardening' },
  { id: 's5', name: 'Stakeholder view polish',     active: false, open: 2,  pr_state: null,     branch: 'stake/polish' },
  { id: 's6', name: 'Idea dump · LAN mobile',      active: false, open: 5,  pr_state: null,     branch: null },
];

const TAGS = {
  runtime:    { name: 'runtime',    color: 'info' },
  ui:         { name: 'ui',         color: 'accent' },
  gates:      { name: 'gates',      color: 'warn' },
  drift:      { name: 'drift',      color: 'warn' },
  audit:      { name: 'audit',      color: 'ghost' },
  perf:       { name: 'perf',       color: 'ok' },
  bundle:     { name: 'bundle',     color: 'info' },
  docs:       { name: 'docs',       color: 'ghost' },
  rag:        { name: 'rag',        color: 'accent' },
  github:     { name: 'github',     color: 'ghost' },
};

// Items — covering open / in-progress / blocked / done across two types (todo, decision).
const ITEMS = [
  {
    id: 'TL-412', type: 'todo', status: 'in_progress',
    title: 'Periodic-review surface — buckets render w/ AI-on toggle',
    description: `Bucket layout per CODE_SPEC §17.

- code-drift, discipline-drift, orphaned-rules → static
- stale-decisions / untouched-sessions / longest-blockers → query-driven
- AI summarise: opt-in toggle, defaults off (cost-aware)

Open question: should bucket counts hyperlink to the source view or expand inline? Inline feels lighter but breaks the everything-is-an-item-list rule.`,
    tags: ['ui', 'runtime'],
    anchor: 'T-D22',
    phase: 'doc-readiness',
    primary_unit: 'periodic_review',
    blocker_text: null,
    blockers: [],
    branch: 'phase/15-hygiene',
    pr: { number: 412, state: 'review', url: '#' },
    stale_days: null,
    drift_tier: null,
    audit: [
      { when: '2026-05-17 09:14', actor: 'user', what: 'status', from: 'todo', to: 'in_progress' },
      { when: '2026-05-17 09:14', actor: 'user', what: 'branch_ref', to: 'phase/15-hygiene' },
      { when: '2026-05-16 16:38', actor: 'ai_extraction', what: 'created', to: 'extracted from dump zone' },
    ],
    sessions: ['s1'],
    code_refs: [
      { path: 'packages/backend/src/intelligence/periodic-review.ts', sym: 'buckets', line: 84 },
      { path: 'packages/frontend/src/views/IntelligenceView.tsx', sym: 'PeriodicReview', line: 12 },
    ],
    notes: ['Periodic-review UX sketch'],
  },
  {
    id: 'TL-408', type: 'todo', status: 'blocked',
    title: 'Orphan-rule one-click cleanup PR — draft branch naming convention',
    description: 'Draft PR branches `throughline/orphan-cleanup-<rule-id>` per T-D26. Blocked: methodology team wants a confirm step before branch push.',
    tags: ['gates', 'github'],
    anchor: 'T-D26',
    phase: 'doc-readiness',
    primary_unit: 'orphan_rules',
    blocker_text: 'Awaiting confirm-step decision from methodology team',
    blockers: [{ id: 'TL-411', title: 'Confirm-before-push pattern decision' }],
    branch: null,
    pr: null,
    stale_days: 6,
    drift_tier: null,
    audit: [
      { when: '2026-05-11 11:02', actor: 'user', what: 'status', from: 'todo', to: 'blocked' },
      { when: '2026-05-11 11:02', actor: 'user', what: 'blocker_text', to: 'Awaiting confirm-step decision…' },
    ],
    sessions: ['s1'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-411', type: 'decision', status: 'open',
    title: 'Confirm-before-push pattern for orphan-rule cleanup PRs',
    description: 'Pick a convention: silent push (fast, scary), interactive confirm (slow, safe), or two-step diff-preview (compromise).',
    tags: ['gates', 'docs'],
    anchor: 'T-D44',
    phase: null,
    primary_unit: 'orphan_rules',
    blocker_text: null,
    blockers: [],
    branch: null,
    pr: null,
    stale_days: 3,
    drift_tier: null,
    audit: [
      { when: '2026-05-14 10:15', actor: 'user', what: 'created' },
    ],
    sessions: ['s1', 's3'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-405', type: 'todo', status: 'done',
    title: 'Sequencing: deprioritise items in failing-gate primary units',
    description: 'Implemented — gate firings → primary unit map → sink in sort. Verified by sequencing.test.ts case 4.',
    tags: ['runtime'],
    anchor: 'C-D9',
    phase: 'code-PR',
    primary_unit: 'sequencing',
    blocker_text: null,
    blockers: [],
    branch: 'sequence/gate-aware',
    pr: { number: 405, state: 'merged', url: '#' },
    stale_days: null,
    drift_tier: 3,
    drift_reason: 'PR #418 touches `intelligence/sequencing.ts` — re-verify',
    audit: [
      { when: '2026-05-09 17:02', actor: 'github_auto_apply', what: 'status', from: 'in_progress', to: 'done', pr: 405 },
    ],
    sessions: ['s1'],
    code_refs: [
      { path: 'packages/backend/src/intelligence/sequencing.ts', sym: 'doNext', line: 142 },
    ],
    notes: [],
  },
  {
    id: 'TL-402', type: 'todo', status: 'todo',
    title: 'Stakeholder render cache: invalidate on item edit',
    description: 'Audit-trail-as-cache, fingerprint by sha256(title+description+status). Spec adopted §13 default.',
    tags: ['rag', 'audit'],
    anchor: 'T-D24',
    phase: null,
    primary_unit: 'stakeholder_view',
    blocker_text: null,
    blockers: [],
    branch: null,
    pr: null,
    stale_days: null,
    drift_tier: null,
    audit: [{ when: '2026-05-12 14:08', actor: 'ai_reconcile', what: 'created' }],
    sessions: ['s5'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-401', type: 'todo', status: 'todo',
    title: 'Drift inbox: tier-4 dedup auto-dismiss after 7 days',
    description: 'Cosine ≥ 0.80 trigger, AI confirmation on 0.70–0.80, auto-dismiss audit reason "stale-no-action".',
    tags: ['drift'],
    anchor: 'T-D21',
    phase: null,
    primary_unit: 'drift_engine',
    blocker_text: null,
    blockers: [],
    branch: null,
    pr: null,
    stale_days: null,
    drift_tier: null,
    audit: [],
    sessions: ['s2'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-398', type: 'todo', status: 'in_progress',
    title: 'Banned-string sweep: regex escape bug on `[UNRESOLVED-(b/c)]`',
    description: 'The marker grammar uses `(b/c)` literally — current regex eats the `/`. Replace with literal class.',
    tags: ['gates', 'bundle'],
    anchor: 'T-D42',
    phase: 'code-PR',
    primary_unit: 'banned_string_sweep',
    blocker_text: null,
    blockers: [],
    branch: 'drift/cleanup',
    pr: null,
    stale_days: null,
    drift_tier: null,
    audit: [
      { when: '2026-05-17 08:30', actor: 'user', what: 'status', from: 'todo', to: 'in_progress' },
    ],
    sessions: ['s2'],
    code_refs: [
      { path: 'packages/backend/src/discipline-drift/banned-string.ts', sym: 'sweep', line: 48 },
    ],
    notes: [],
  },
  {
    id: 'TL-393', type: 'decision', status: 'locked',
    title: 'Gate findings stream: one stream per gate, not per moment',
    description: 'Locked 2026-05-04. SiteMesh per-commit moment has two gates (verify-structure.sh + banned-string-sweep); each emits its own findings. Companion runtime mirrors this.',
    tags: ['gates'],
    anchor: 'T-D44',
    phase: null,
    primary_unit: 'gate_runtime',
    blocker_text: null,
    blockers: [],
    branch: null,
    pr: null,
    stale_days: null,
    drift_tier: null,
    audit: [{ when: '2026-05-04 16:00', actor: 'user', what: 'status', from: 'open', to: 'locked' }],
    sessions: ['s3'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-389', type: 'todo', status: 'in_progress',
    title: 'Cost meter: warn at daily threshold; quiet thereafter',
    description: 'Header pill turns danger when daily spend exceeds configurable threshold. One warning per day, then quiet — no nag.',
    tags: ['ui', 'perf'],
    anchor: 'T-D29',
    phase: 'doc-readiness',
    primary_unit: 'cost_meter',
    blocker_text: null,
    blockers: [],
    branch: 'phase/15-hygiene',
    pr: null,
    stale_days: null,
    drift_tier: null,
    audit: [],
    sessions: ['s1'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-385', type: 'todo', status: 'blocked',
    title: 'Per-list chat panel: token budget enforcement',
    description: 'Sonnet 200k context but session digest can exceed budget on large projects. Truncate by relevance, not chronology.',
    tags: ['rag'],
    anchor: null,
    phase: null,
    primary_unit: 'chat',
    blocker_text: 'Need router heuristic confirmed by RAG owner',
    blockers: [],
    branch: null,
    pr: null,
    stale_days: 9,
    drift_tier: null,
    audit: [],
    sessions: ['s1'],
    code_refs: [],
    notes: [],
  },
  {
    id: 'TL-380', type: 'todo', status: 'done',
    title: 'Companion runtime: judgement step → ask AI handoff',
    description: 'Sonnet-based judgement with prompt fingerprint + cost row.',
    tags: ['runtime'],
    anchor: 'C-D8',
    phase: 'code-PR',
    primary_unit: 'companion_runtime',
    blocker_text: null,
    blockers: [],
    branch: 'companion/hardening',
    pr: { number: 380, state: 'merged', url: '#' },
    stale_days: null,
    drift_tier: 1,
    drift_reason: 'Semgrep rule `tl-380-judgement-fingerprint.yml` failed on latest CI',
    audit: [{ when: '2026-05-08 12:00', actor: 'github_auto_apply', what: 'status', from: 'in_progress', to: 'done', pr: 380 }],
    sessions: ['s4'],
    code_refs: [
      { path: 'packages/backend/src/methodology/companion/engine.ts', sym: 'aiJudgeStep', line: 220 },
    ],
    notes: [],
  },
];

// Drift signals
const DRIFT = [
  {
    id: 'd1', stream: 'code', tier: 1,
    item: 'TL-380', item_title: 'Companion runtime: judgement step → ask AI handoff',
    reason: 'Semgrep rule `tl-380-judgement-fingerprint.yml` failed on PR #422',
    pr: 422, when: '17 May · 09:02',
    ai_reverify: null,
  },
  {
    id: 'd2', stream: 'code', tier: 2,
    item: 'TL-371', item_title: 'GitHub poller — ETag 304 short-circuit',
    reason: 'Revert PR #420 reverted #371 — code regressed',
    pr: 420, when: '16 May · 22:14',
    ai_reverify: '"appears regressed" · Sonnet · conf 0.86',
  },
  {
    id: 'd3', stream: 'code', tier: 3,
    item: 'TL-405', item_title: 'Sequencing: deprioritise items in failing-gate primary units',
    reason: 'PR #418 touches `intelligence/sequencing.ts` — re-verify',
    pr: 418, when: '16 May · 18:40',
    ai_reverify: null,
  },
  {
    id: 'd4', stream: 'code', tier: 3,
    item: 'TL-356', item_title: 'Text RAG: incremental embedding re-index',
    reason: 'PR #417 touches `intelligence/text-index.ts`',
    pr: 417, when: '16 May · 17:11',
    ai_reverify: null,
  },
  {
    id: 'd5', stream: 'code', tier: 4,
    item: null, item_title: '(dump zone proposal: "embed pipeline batches w/ progress")',
    reason: 'Cosine 0.84 vs done item TL-356 — likely duplicate',
    pr: null, when: '15 May · 11:30',
    ai_reverify: '"still looks done" · Sonnet · conf 0.91',
  },
  {
    id: 'd6', stream: 'discipline', tier: null,
    category: 'banned_string',
    item: 'TL-398', item_title: 'Banned-string sweep: regex escape bug',
    reason: 'Live `[UNRESOLVED-(b/c)]` marker in `SPEC.md §7.14` past doc-readiness',
    when: '17 May · 08:18',
    primary_unit: 'banned_string_sweep',
  },
  {
    id: 'd7', stream: 'discipline', tier: null,
    category: 'cross_reference',
    item: 'TL-402', item_title: 'Stakeholder render cache',
    reason: 'Anchor T-D24 cited but body references the v5.0 numbering — superseded',
    when: '16 May · 14:00',
    primary_unit: 'stakeholder_view',
  },
  {
    id: 'd8', stream: 'discipline', tier: null,
    category: 'structural',
    item: null,
    item_title: 'methodologies/test-bundle/bundle.md',
    reason: 'Section 5 (state machine) declares 4 phases but only 3 are templated in §9',
    when: '15 May · 19:22',
    primary_unit: null,
  },
];

// Gate firings
const GATE_FIRINGS = [
  {
    moment: 'pre-write', key: 'cited-anchors-resolve',
    status: 'pass', when: '17 May · 09:14', target: 'TL-412 description draft',
    findings: [],
  },
  {
    moment: 'pre-write', key: 'sub-agent-linenum-check',
    status: 'pass', when: '17 May · 09:14', target: 'TL-412 description draft',
    findings: [],
  },
  {
    moment: 'per-commit', key: 'verify-structure.sh',
    status: 'fail', when: '17 May · 08:42', target: 'commit a1b2c3d on phase/15-hygiene',
    findings: [
      { msg: 'Module `periodic_review` is missing required file: REVIEW_NOTES.md', loc: 'methodologies/test-bundle/modules/periodic_review' },
      { msg: 'Section ordering: §3 (anchor system) appears after §4 (markers)', loc: 'bundle.md:104' },
    ],
  },
  {
    moment: 'per-commit', key: 'banned-string-sweep',
    status: 'fail', when: '17 May · 08:42', target: 'commit a1b2c3d on phase/15-hygiene',
    findings: [
      { msg: 'banned string `[UNRESOLVED-(b/c)]` introduced past doc-readiness', loc: 'SPEC.md:412' },
    ],
  },
  {
    moment: 'plan-mode', key: 'plan-shape',
    status: 'pass', when: '17 May · 09:01', target: 'Plan mode · phase/15-hygiene',
    findings: [],
  },
  {
    moment: 'post-commit', key: 'no-banned-strings',
    status: 'skipped', when: '17 May · 08:42', target: 'commit a1b2c3d',
    findings: [{ msg: 'Skipped: per-commit gate failed (run override+retry to lift)', loc: '' }],
  },
  {
    moment: 'post-commit', key: 'citations-still-resolve',
    status: 'pass', when: '17 May · 08:38', target: 'commit f4e5d6a',
    findings: [],
  },
  {
    moment: 'pr-open', key: 'no-live-unresolved-markers',
    status: 'pass', when: '16 May · 22:30', target: 'PR #420',
    findings: [],
  },
];

const PUSHES = [
  { when: '09:14', what: 'Phase 15 — periodic-review buckets PR draft', ref: 'cc_2026-05-17_0914.md', accent: true },
  { when: '08:42', what: 'Per-commit gates failed × 2 — review proposals', ref: 'gate_firing × 2', accent: false },
  { when: '08:30', what: 'Banned-string regex bug found', ref: 'TL-398 created', accent: false },
  { when: 'yesterday', what: 'GitHub revert on TL-371 — tier-2 drift', ref: 'PR #420 revert', accent: false },
  { when: 'yesterday', what: 'Phase 14d chat-mode handover saved to library', ref: 'note_2026-05-16.md', accent: false },
];

const PRIMARY_UNITS = [
  { id: 'periodic_review',    name: 'periodic_review',     tier: 1, phase: 'doc-readiness', items: 4, anchors: 6, markers: 1, drift: 0 },
  { id: 'orphan_rules',       name: 'orphan_rules',        tier: 2, phase: 'doc-readiness', items: 2, anchors: 3, markers: 0, drift: 0 },
  { id: 'drift_engine',       name: 'drift_engine',        tier: 1, phase: 'code-PR',       items: 6, anchors: 9, markers: 0, drift: 0 },
  { id: 'gate_runtime',       name: 'gate_runtime',        tier: 1, phase: 'shipped',       items: 9, anchors: 12, markers: 0, drift: 2 },
  { id: 'sequencing',         name: 'sequencing',          tier: 2, phase: 'shipped',       items: 3, anchors: 4, markers: 0, drift: 1 },
  { id: 'banned_string_sweep',name: 'banned_string_sweep', tier: 2, phase: 'code-PR',       items: 2, anchors: 2, markers: 1, drift: 1 },
  { id: 'companion_runtime',  name: 'companion_runtime',   tier: 1, phase: 'shipped',       items: 5, anchors: 7, markers: 0, drift: 1 },
];

const NOTES_COUNT = 47;
const SCRATCHPAD_JOTS = 3;

Object.assign(window, {
  PROJECT, SESSIONS, TAGS, ITEMS, DRIFT, GATE_FIRINGS, PUSHES, PRIMARY_UNITS,
  NOTES_COUNT, SCRATCHPAD_JOTS,
});
